-- MySQL Script generated by MySQL Workbench
-- Sun Nov  1 23:09:33 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

drop database ventas; 

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ventas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ventas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ventas` DEFAULT CHARACTER SET utf8mb4 ;
USE `ventas` ;

-- -----------------------------------------------------
-- Table `ventas`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas`.`usuarios` (
  `id_usuario` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NULL DEFAULT NULL,
  `apellido` VARCHAR(50) NULL DEFAULT NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  `password` TINYTEXT NULL DEFAULT NULL,
  `fechaCaptura` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ventas`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas`.`categorias` (
  `id_categoria` INT(11) NOT NULL AUTO_INCREMENT,
  `nombreCategoria` VARCHAR(150) NULL DEFAULT NULL,
  `fechaCaptura` DATE NULL DEFAULT NULL,
  `id_usuario` INT(11) NOT NULL,
  PRIMARY KEY (`id_categoria`),
  CONSTRAINT `fk_categorias_usuarios1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `ventas`.`usuarios` (`id_usuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ventas`.`imagenes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas`.`imagenes` (
  `id_imagen` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(500) NULL DEFAULT NULL,
  `ruta` VARCHAR(500) NULL DEFAULT NULL,
  `fechaSubida` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id_imagen`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ventas`.`articulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas`.`articulos` (
  `id_producto` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NULL DEFAULT NULL,
  `descripcion` VARCHAR(500) NULL DEFAULT NULL,
  `cantidad` INT(11) NULL DEFAULT NULL,
  `precio` FLOAT NULL DEFAULT NULL,
  `fechaCaptura` DATE NULL DEFAULT NULL,
  `puntos` INT(11) NULL DEFAULT 0,
  `id_categoria` INT(11) NOT NULL,
  `id_imagen` INT(11) NOT NULL,
  `id_usuario` INT(11) NOT NULL,
  PRIMARY KEY (`id_producto`),
  CONSTRAINT `fk_articulos_categorias1`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `ventas`.`categorias` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_articulos_imagenes1`
    FOREIGN KEY (`id_imagen`)
    REFERENCES `ventas`.`imagenes` (`id_imagen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_articulos_usuarios1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `ventas`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ventas`.`caja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas`.`caja` (
  `idCaja` INT(11) NOT NULL AUTO_INCREMENT,
  `num` INT(11) NULL DEFAULT NULL,
  `descripcion` VARCHAR(75) NULL DEFAULT NULL,
  PRIMARY KEY (`idCaja`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ventas`.`caja_ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas`.`caja_ventas` (
  `idCajaVentas` INT(11) NOT NULL AUTO_INCREMENT,
  `fechaApertura` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `fechaCierre` TIMESTAMP NULL DEFAULT NULL,
  `observaciones` VARCHAR(150) NULL DEFAULT NULL,
  `saldoInicial` FLOAT NULL DEFAULT NULL,
  `idcaja` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idCajaVentas`),
  CONSTRAINT `caja_ventas_ibfk_1`
    FOREIGN KEY (`idcaja`)
    REFERENCES `ventas`.`caja` (`idCaja`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ventas`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas`.`clientes` (
  `id_cliente` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(200) NULL DEFAULT NULL,
  `apellido` VARCHAR(200) NULL DEFAULT NULL,
  `direccion` VARCHAR(200) NULL DEFAULT NULL,
  `email` VARCHAR(200) NULL DEFAULT NULL,
  `telefono` VARCHAR(200) NULL DEFAULT NULL,
  `nit` VARCHAR(200) NULL DEFAULT NULL,
  `puntos` INT(11) NULL DEFAULT 0,
  `id_usuario` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_cliente`),
  CONSTRAINT `fk_clientes_usuarios1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `ventas`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ventas`.`cupones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas`.`cupones` (
  `idCupon` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(75) NULL DEFAULT NULL,
  `descripcion` VARCHAR(255) NULL DEFAULT NULL,
  `cantidad` INT(11) NULL DEFAULT NULL,
  `utilizados` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idCupon`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ventas`.`cupones_ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas`.`cupones_ventas` (
  `idCuponesVentas` INT(11) NOT NULL AUTO_INCREMENT,
  `idCupon` INT(11) NULL DEFAULT NULL,
  `idVenta` INT(11) NULL DEFAULT NULL,
  `img` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`idCuponesVentas`),
  CONSTRAINT `cupones_ventas_ibfk_1`
    FOREIGN KEY (`idCupon`)
    REFERENCES `ventas`.`cupones` (`idCupon`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ventas`.`ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas`.`ventas` (
  `id_venta` INT(11) NOT NULL,
  `precio` FLOAT NULL DEFAULT NULL,
  `fechaCompra` DATE NULL DEFAULT NULL,
  `tipo_pago` VARCHAR(2) NULL DEFAULT NULL,
  `idCajaVentas` INT(11) NULL DEFAULT NULL,
  `id_producto` INT(11) NOT NULL,
  `id_usuario` INT(11) NOT NULL,
  `id_cliente` INT(11) NOT NULL,
  CONSTRAINT `ventas_ibfk_1`
    FOREIGN KEY (`idCajaVentas`)
    REFERENCES `ventas`.`caja_ventas` (`idCajaVentas`),
  CONSTRAINT `fk_ventas_articulos1`
    FOREIGN KEY (`id_producto`)
    REFERENCES `ventas`.`articulos` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ventas_usuarios1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `ventas`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ventas_clientes1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `ventas`.`clientes` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

drop table ventas;
drop table clientes;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

use ventas;

INSERT INTO caja VALUES (1,0,'Caja 0'),(2,1,'Caja 1');
INSERT INTO cupones VALUES (1,'CAMP001','CUPON POR 1 Menu Super Campero',998,0),(2,'DESC10','CUPON POR 10% descuento en Tiendas Max Distelsa',999,0),(3,'DESCINT10','CUPON POR 10% descuento en mercaderia Intelaf',999,0);

describe clientes;
insert into clientes(nombre, nit) values('C/F', 'C/F');



